# Basic
title: Vno Jekyll
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/BruceChen5683/BruceChen5683.github.io" target="_blank">Download the theme</a>
description: 测试github搭建网站
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: QQ空间, description: My Projects, url: 'https://user.qzone.qq.com/605385881'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: BattleCall1990
    github: BruceChen5683
    mail: 605385881@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
